language: swift
osx_image: xcode10.2
script: xcodebuild -workspace LightMVVMC.xcworkspace -scheme LightMVVMC -destination 'platform=iOS Simulator,name=iPhone X' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
